# Generated by Django 5.0.2 on 2024-03-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
