# Generated by Django 5.0.2 on 2024-03-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0004_getdevice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getDevice',
            new_name='Devices',
        ),
    ]
