# Generated by Django 5.0.2 on 2024-03-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0006_rename_devices_smarthphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarthphone',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
