# Generated by Django 5.0.2 on 2024-03-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0008_smarthphone_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarthphone',
            old_name='name',
            new_name='names',
        ),
    ]
