# Generated by Django 5.0.2 on 2024-03-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0009_rename_name_smarthphone_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='names',
        ),
    ]
