# Generated by Django 5.0.2 on 2024-03-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0010_rename_name_device_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='names',
            new_name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='memory',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
