# Generated by Django 5.0.2 on 2024-03-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0011_rename_names_device_name_device_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarthphone',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='smarthphone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='smarthphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smarthphone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='smarthphone',
            name='updated',
        ),
    ]
