# Generated by Django 5.0.2 on 2024-03-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0012_rename_price_smarthphone_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_order', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.IntegerField()),
                ('manufacturer_code', models.CharField(max_length=20)),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('model_code', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('model_title', models.CharField(max_length=100)),
                ('category_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webscrapper.categoryitem')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscrapper.manufacturer')),
            ],
        ),
    ]
