# Generated by Django 5.0.2 on 2024-03-11 00:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0013_categoryitem_manufacturer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceprices',
            name='device',
        ),
        migrations.RemoveField(
            model_name='review',
            name='device',
        ),
        migrations.DeleteModel(
            name='Smarthphone',
        ),
        migrations.AddField(
            model_name='model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.CharField(default='https://www.gizmochina.com/wp-content/uploads/2020/12/1-14-300x300.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelprices',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='webscrapper.model'),
        ),
        migrations.DeleteModel(
            name='DevicePrices',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
