# Generated by Django 5.0.2 on 2024-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0014_modelprices_remove_deviceprices_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='buyback_value_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
