# Generated by Django 5.0.2 on 2024-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0015_model_buyback_value_max'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelPrices',
            new_name='ModelPrice',
        ),
    ]
