# Generated by Django 5.0.2 on 2024-03-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0016_rename_modelprices_modelprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelprice',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='model',
            name='buyback_value_max',
        ),
        migrations.AlterField(
            model_name='modelprice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
