# Generated by Django 5.0.2 on 2024-03-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0019_alter_modelprice_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprice',
            name='model_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
