# Generated by Django 5.0.2 on 2024-03-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0020_alter_modelprice_model_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='model_id',
        ),
    ]
