# Generated by Django 5.0.2 on 2024-03-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0021_remove_model_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
